# Generated by Django 5.0.1 on 2024-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
