# Generated by Django 5.0.1 on 2024-01-22 09:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)])),
                ('experience_age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('otp_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chef_type', models.CharField(choices=[('wet', 'wet maker'), ('dry', 'dry maker'), ('cake', 'cake maker'), ('bread', 'bread maker'), ('none', 'not a chef')], default='none', max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
