# Generated by Django 5.0.1 on 2024-02-11 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_profile_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience_age',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)]),
        ),
    ]
