# Generated by Django 5.0.1 on 2024-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('brand', models.ImageField(upload_to='brands')),
                ('background_image', models.ImageField(upload_to='backgrounds')),
                ('default_product_image', models.ImageField(upload_to='default_image_products')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
