# Generated by Django 5.0.1 on 2024-02-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='brand',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='default_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='default_image_products'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(default='setting', max_length=300),
        ),
    ]
