# Generated by Django 5.0.1 on 2024-01-22 09:41

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, default='default.png', null=True, upload_to='pictures')),
                ('deposit', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('wet', 'wet'), ('cake', 'cake'), ('dry', 'dry'), ('bread', 'bread'), ('outhers', 'outhers')], default='dry', max_length=15)),
                ('time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('pastry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
